class DriverAvailabilityService:

    def get_available_drivers(self):
        ...
    def book_driver(self):
        ...
    def cancel_trip(self):
        ...
    def mark_on_trip(self):
        ...