
class PieceStrategy:
    ...

class RookStrategy(PieceStrategy):
    ...
class KnightStrategy(PieceStrategy):
    ...
class BishopStrategy(PieceStrategy):
    ...
class QueenStrategy(PieceStrategy):
    ...
class KingStrategy(PieceStrategy):
    ...
class PawnStrategy(PieceStrategy):
    ...